#pusher

pusher_app_id: '884785'
pusher_key: '8f6949c601c154628e1b'
pusher_secret: '814c5b2a0014f58b3278'
pusher_cluster: 'us2'
REDIS_URL: 'redis:://127.0.0.1:6379'

#fb app
fb_verify_token: ''
fb_app_secret: ''
fb_app_id: ''

#ses

ses_address:
ses_username:
ses_password:

#misc
frontend_url: ''

#s3

S3_BUCKET_NAME: ''
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
AWS_REGION: ''


#chargebee
CHARGEBEE_API_KEY: ''
CHARGEBEE_SITE: ''
CHARGEBEE_WEBHOOK_USERNAME: ''
CHARGEBEE_WEBHOOK_PASSWORD: ''

#sentry
SENTRY_DSN: ''

